In [1]:
import numpy as np
import matplotlib.pyplot as plt
# from matplotlib.pyplot import *
# from sklearn.neural_network import MLPClassifier as sk
import time

In [2]:
# X = (hours sleeping, hours studying), y = Score on test
X = np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75], [82], [93]), dtype=float)
X

array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [3]:
X = X/np.amax(X, axis=0)  # ???????
y = y/100 # Max test score is 100
X


array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [4]:
y

array([[0.75],
       [0.82],
       [0.93]])

In [5]:
class Neural_Network(object):
    def __init__(self):        
        # Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        # Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        #Propagate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    

In [17]:
NN = Neural_Network()
NN.W1

array([[ 0.41484396, -0.19476076, -0.38495089],
       [-1.70756185,  1.73916878,  0.12174442]])

In [18]:

NN.W1[0,0] = 1.1
yHat = NN.forward(X)

In [19]:
np.sum(0.5*(y-yHat)**2)

0.3278211018747147